config/routes.rb
Rails.application.routes.draw do

  resources :change_password,			only: [:new, :create, :edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :orders, only: [:new, :create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users do
    get "/login" => "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/pages/order_success", "pages#order_success"
  put '/order_items/update',        to: 'order_items#update_item'

  root "pages#home"
end

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lexicon</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body class="transparent home welcompage">
    <div class="bodyBg"></div>
    <div class="overlayBlue"></div>
    <div class="pageWrap">
        <!-- Header -->
        <div class="header rPos">
            <div class="grid rPos">
                <div class="row">
                    <div class="c2">
                        <div class="logo">
                            <a href="/"><%= image_tag "logo.png", alt: 'Lexicon' %></a>
                        </div>
                    </div>

                    <div class="c10">
                        <div class="navigation">
                            <ul>
                                <li>
                                  <%= mail_to support_email, "SUPPORT", class: 'primaryButton' %>&nbsp;
                                  <% if current_user -%>
                                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "primaryButton" -%>
                                    <%= link_to "Profile", new_change_password_path, class: "primaryButton secondaryColor" -%>
                                  <% else -%>  
                                    <%= link_to "Log in", new_session_path(:user), class: 'primaryButton' %>
                                  <% end -%>  
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div class="main rPos primaryColor home-page-intro">
            <div class="grid">
                <div class="row">
                    <div class="c12">
                        <h1>Welcome to Lexicon Resource Center. </h1>

                        <p>This site will handle all of your resource material needs for <%= image_tag "xermelo-nobackround.png", class: "xermela-logo"%>.</p>
                        <p>If you should need assistance, please contact us using the support button.</p>
                        <p>All orders are shipped using Fed Ex ground delivery. If you need rush fulfillment please contact support.</p>
                        <%= link_to "Start Ordering Materials Now", new_order_path, class: 'primaryButton white-color-btn'%>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="footer rPos">
        <div class="grid">
            <div class="row">
                <div class="c2">
                    <div class="footerLogo">
                      <%= image_tag "logo.png", alt: 'Lexicon' %>
                    </div>
                </div>
                <div class="c10">
                    <p>Corporate Headquarters: 8800 Technology Forest Place • The Woodlands, Texas 77381-1160</p>
                    <p>Phone: 281.863.3000 | Toll Free: 855.828.4651 | Fax: 281.863.8088</p>
                </div>
            </div>
        </div>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>

</html>

app/views/pages/order_success.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success - Lexicon</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body class="vilotBgColor success orderFinal">
    <div class="pageWrap">
        <!-- Header -->
        <div class="header rPos">
            <div class="headerBg"></div>
            <div class="overlayVilot"></div>
            <div class="grid rPos">
                <div class="row">
                    <div class="c2">
                        <div class="logo">
                            <a href="/"><%= image_tag "logo.png", alt: 'Lexicon' %></a>
                        </div>
                    </div>

                    <div class="c10">
                        <div class="navigation">
                            <ul>
                                <li>
                                  <%= mail_to support_email, "SUPPORT", class: 'primaryButton' %>&nbsp;
                                  <% if current_user -%>
                                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "primaryButton" -%>
                                  <% else -%>  
                                    <%= link_to "Log in", new_session_path(:user), class: 'primaryButton' %>
                                  <% end -%>  
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div class="main rPos primaryColor">
            <div class="grid">
                <div class="row">
                    <div class="c12">
                        <h1><%= post_order_title @order -%></h1>
                        <p>
                          
                          <p>
                            Order Details:<br/><br/>
                            <span style="font-size:20px;text-transform: uppercase;">Order ID# <%= @order.id -%></span><br/>
                            <% @order.order_items.each do |li| %>
                              <% high_qty_css = (@order.waiting_approval? && li.high_quantity?) ? "color:#f44336;" : "" -%>
                              <span style="<%= high_qty_css -%>"><%= "#{li.product.name} - Quantity: #{li.quantity}"%></span>
                              <br/>
                            <% end -%>
                          </p>

                          <strong>Shipping Info:</strong>
                          <br/>
                          <%= current_user.full_name -%><br/>
                          <%= current_user.full_address.html_safe -%><br/><br/>
                          Your order is being shipped through Fed Ex One Rate. Please allow 2-4 business days.
                          <br/>
                          
                          Make an error? Need to change something? Please contact support
                          <br/><br/>
                          *Resources marked ON HOLD are currently back-ordered. They will be shipped when inventory is in stock.
                          <br/>
                          <% if @order.waiting_approval? %>
                            <br/>
                            <div class="error-container-2">
                              <span class="error-msg">
                                <strong>*</strong> Resources that appear red require approval. You will receive an email if approved or rejected.
                              </span>
                            </div>
                          <% end -%>
                          
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="footer rPos">
        <div class="grid">
            <div class="row">
                <div class="c2">
                    <div class="footerLogo">
                        <%= image_tag "logo.png", alt: 'Lexicon' %>
                    </div>
                </div>
                <div class="c10">
                    <p>Corporate Headquarters: 8800 Technology Forest Place • The Woodlands, Texas 77381-1160</p>
                    <p>Phone: 281.863.3000 | Toll Free: 855.828.4651 | Fax: 281.863.8088</p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>