config/routes.rb
Rails.application.routes.draw do

  resources :change_password,			only: [:new, :create, :edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :orders, only: [:new, :create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users do
    get "/login" => "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/pages/order_success", "pages#order_success"
  put '/order_items/update',        to: 'order_items#update_item'

  root "pages#home"
end

app/controllers/change_password_controller.rb
class ChangePasswordController < ApplicationController
  
  before_action :authenticate_user!
  
  def new
	  
	  create
	  
  end

	def create
		#current_password = params[:change_password][:password]
		
    #hashed_password = BCrypt::Password.create(current_password)
		
		
		
    @user = current_user
    if @user #&& BCrypt::Password.new(@user.password) == params[:change_password][:password]
      @user.create_reset_digest
      redirect_to edit_password_reset_url(@user.reset_token, email: @user.email)
    else
      flash.now[:danger] = "Invalid Current Password"
      render 'new'
    end
  end

  def edit
  end
  
end

app/helpers/change_password_helper.rb
module ChangePasswordHelper
end

app/views/change_password/edit.html.erb
<h1>ChangePassword#edit</h1>
<p>Find me in app/views/change_password/edit.html.erb</p>

app/views/change_password/new.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lexicon - Change Password</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body class="transparent home welcompage">
    <div class="bodyBg"></div>
    <div class="overlayBlue"></div>
    <div class="pageWrap">
        <!-- Header -->
        <div class="header rPos">
            <div class="grid rPos">
                <div class="row">
                    <div class="c2">
                        <div class="logo">
                            <a href="/"><%= image_tag "logo.png", alt: 'Lexicon' %></a>
                        </div>
                    </div>

                    <div class="c10">
                        <h1 class="primaryColor headerTitle">Lexicon Resource and Materials Center</h1>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div class="main rPos primaryColor">
            <div class="grid">
                <div class="row">
                    <div class="c16 s3">
                    
												<h1>Change password</h1>

												<div class="row">
												  <div class="col-md-6 col-md-offset-3">
												    <%= form_for( :change_password, url: change_password_index_path) do |f| %>
												    <div style="color:#e91e63;font-size:17px;padding-left:5px;background:#fff;line-height:30px;width:600px;">
		                          <% if request.post? -%>
		                            <%= image_tag "/error-icon.png", size: "18x18", style: "display:inline;"%>&nbsp; Your password is incorrect. 
		                          <% end -%>
		                        </div>
												      
												      <%= f.label :password %><br />
												      <%= f.password_field :password, autofocus: true %>
												      
												      <div class="actions">
												      	<%= f.submit "Submit", id: "change-password-form-submit", style: "display:block;",  class: "btn btn-primary" %>
												      	<a class="primaryButton" style="display:block;width:120px;text-align:center;" href="#" onclick="document.getElementById('change-password-form-submit').click();return false;">Submit</a>
												      </div>
												    <% end %>
												  </div>
												</div>
                    
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <!-- Footer -->
    <div class="footer rPos">
        <div class="grid">
            <div class="row">
                <div class="c2">
                    <div class="footerLogo">
                        <%= image_tag "logo.png", alt: 'Lexicon' %>
                    </div>
                </div>
                <div class="c10">
                    <p>Corporate Headquarters: 8800 Technology Forest Place &bull; The Woodlands, Texas 77381-1160</p>
                    <p>Phone: 281.863.3000 | Toll Free: 855.828.4651 | Fax: 281.863.8088</p>
                </div>
            </div>
        </div>
    </div>
    
    
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
</body>
</html>